package: stellenangebote
version: '0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/stellenangebote


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"



page:
    title: translate:stellenangebote_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    stellenangebote:
        title: translate:stellenangebote_title

        block: system
        prio: 15
        icon: rex-icon fa-magnet
        perm: stellenangebote[]
        subpages:
            table:
                title: translate:stellenangebote_table
                icon: rex-icon fa-magnet
                itemclass: pull-right
                perm: admin
            settings:
                title: translate:stellenangebote_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:stellenangebote_docs
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: stellenangebote[docs]

default_config:
    company_name: ''
    company_url: ''
