package: stellenangebote
version: '2.0.4'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/stellenangebote

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13
    packages:
        accessdenied: ">=1"
        auto_delete: ">=0"
        yform: "^4"
        yform_spam_protection: "^1"
        yform_field: "^2"
        yform_geo_osm: "^1"

page:
    title: translate:stellenangebote_title
    icon: rex-icon fa-magnet
    block: system
    prio: 18

pages:
    stellenangebote:
        title: translate:stellenangebote_title
        icon: rex-icon fa-magnet
        perm: stellenangebote[jobs]
        subpages:
            entry:
                title: translate:stellenangebote_entry
                icon: rex-icon fa-magnet
                perm: stellenangebote[jobs]
            category:
                title: translate:stellenangebote_category
                icon: rex-icon fa-folder
                perm: stellenangebote[jobs]
            benefits:
                title: translate:stellenangebote_benefits
                icon: rex-icon fa-plus
                perm: stellenangebote[jobs]
            contact:
                title: translate:stellenangebote_contact
                icon: rex-icon rex-icon-user
                perm: stellenangebote[jobs]
            location:
                title: translate:stellenangebote_location
                icon: rex-icon fa-map-marker
                perm: stellenangebote[jobs]
    apply:
        title: translate:stellenangebote_apply
        icon: rex-icon fa-file-text-o
        perm: stellenangebote[apply]
        subpages:
            message:
                title: translate:stellenangebote_apply
                icon: rex-icon fa-file-text-o
                perm: stellenangebote[apply]
            custom_message:
                title: translate:stellenangebote_apply_custom
                icon: rex-icon fa-file-text-o
                perm: stellenangebote[apply]
    settings:
        title: translate:stellenangebote_settings
        icon: rex-icon fa-gear
        itemclass: pull-right
        perm: admin
    docs:
        title: translate:stellenangebote_docs
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: stellenangebote[docs]

default_config:
    company_name: ''
    company_url: ''
    editor: 'class="form-control cke5-editor" data-lang="de" data-profile="default"'
    apply_value_id: 
    category_id: 
    thank_you_id: 
